"""Initial migration with users

Revision ID: 665ef2aea657
Revises: 
Create Date: 2026-06-12 16:46:40.630299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665ef2aea657'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('drawings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('points_json', sa.String(), nullable=False),
    sa.Column('style_json', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawings_id'), 'drawings', ['id'], unique=False)
    op.create_index(op.f('ix_drawings_session_id'), 'drawings', ['session_id'], unique=False)
    op.create_index(op.f('ix_drawings_user_id'), 'drawings', ['user_id'], unique=False)
    op.create_table('replay_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('current_time', sa.Integer(), nullable=True),
    sa.Column('playback_speed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_sessions_id'), 'replay_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_replay_sessions_user_id'), 'replay_sessions', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('lots', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_time', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_session_id'), 'trades', ['session_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('trade_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(), nullable=True),
    sa.Column('setup_name', sa.String(), nullable=True),
    sa.Column('mistake_type', sa.String(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('lesson', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_notes_id'), 'trade_notes', ['id'], unique=False)
    op.create_index(op.f('ix_trade_notes_trade_id'), 'trade_notes', ['trade_id'], unique=False)
    op.create_table('trade_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(), nullable=True),
    sa.Column('tag_category', sa.String(), nullable=False),
    sa.Column('tag_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_tags_id'), 'trade_tags', ['id'], unique=False)
    op.create_index(op.f('ix_trade_tags_trade_id'), 'trade_tags', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_tags_trade_id'), table_name='trade_tags')
    op.drop_index(op.f('ix_trade_tags_id'), table_name='trade_tags')
    op.drop_table('trade_tags')
    op.drop_index(op.f('ix_trade_notes_trade_id'), table_name='trade_notes')
    op.drop_index(op.f('ix_trade_notes_id'), table_name='trade_notes')
    op.drop_table('trade_notes')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_session_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_replay_sessions_user_id'), table_name='replay_sessions')
    op.drop_index(op.f('ix_replay_sessions_id'), table_name='replay_sessions')
    op.drop_table('replay_sessions')
    op.drop_index(op.f('ix_drawings_user_id'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_session_id'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_id'), table_name='drawings')
    op.drop_table('drawings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
