"""Add screenshot_url

Revision ID: db75b3049a39
Revises: 665ef2aea657
Create Date: 2026-06-13 11:37:36.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db75b3049a39'
down_revision: Union[str, Sequence[str], None] = '665ef2aea657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_notes', sa.Column('screenshot_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_notes', 'screenshot_url')
    # ### end Alembic commands ###
